name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
        chmod 777 rustup-init.sh
        sh rustup-init.sh -y --default-toolchain none
        source "$HOME/.cargo/env"
        rustup update
        rustup default 1.85.0
        cargo --version
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
